### ISSUE TITLE
Here option is gray in import menu, Unity 2020.2.1f1

### ISSUE THREAD

**Issue by madc0der** [DmitriyYukhanov/Package2Folder#4]
Hello! 
Downloaded and import, got new "Here" option in "Import" menu, but it's grayed.
There are no errors in console.

**Comment by DmitriyYukhanov** [comment]
Hey @madc0der,

Thank you for reporting this!
Please select any folder in your Project Browser's Assets before calling context menu to enable "Here" import menu item.

If you are already trying this in a such way and it's still grayed out, please let me know a bit more about your case:
- what is your exact Unity version?
- does it reproduces in new project?

Thanks!

**Comment by madc0der** [comment]
Hi!

Unity 2020.2.1f1

1. Clear project (no "here" option):
![image](https://user-images.githubusercontent.com/5368643/120081700-8eb23280-c0c7-11eb-8c84-95c02f8798b7.png)

2. Import package from asset store:
![image](https://user-images.githubusercontent.com/5368643/120081707-9b368b00-c0c7-11eb-81f2-56e0e4db4762.png)

3. Option "Here" appeared but grayed:
![image](https://user-images.githubusercontent.com/5368643/120081719-a5f12000-c0c7-11eb-854f-a9ae1d899275.png)

I got it active one time, but all others it remains grayed.

**Comment by DmitriyYukhanov** [comment]
Hey again, @madc0der 

Thank you for additional information. I was able to reproduce it and it's going to be fixed in next update.

For now, please use One-column Project view to workaround this issue:
![image](https://user-images.githubusercontent.com/883587/120100985-6882a600-c14c-11eb-8a68-ccfadce904ca.png)

**Comment by DmitriyYukhanov** [comment]
Fixed with https://github.com/DmitriyYukhanov/Package2Folder/releases/tag/1.0.6
